minVersion: "0.13.2"
github:
  owner: omnivector-solutions
  repo: license-manager
releaseBranchPrefix: release
preReleaseCommand: bash .craft/bump-version.sh
changelog: CHANGELOG.md
changelogPolicy: auto
statusProvider:
  name: github
  config:
    contexts:
      - "ReleaseAction"
artifactProvider:
  name: github
targets:
  - name: github
