example-1:
  server_type: "flexlm"
  port: 24200
  delay: 30
  servers:
    - "licserv0011.scania.com"
    - "licserv0012.scania.com"
    - "licserv0013.scania.com"
  slurm_dbd: "slurmdbd"

example-2:
  server_type: "flexlm"
  port: 24200
  delay: 30
  servers:
    - "licserv0011.scania.com"
    - "licserv0012.scania.com"
    - "licserv0013.scania.com"
  slurm_dbd: "slurmdbd"
