name: 'BuildReleaseEdge'

on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Build the license-manager snap"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: "Install Snapcraft"
        uses: samuelmeuli/action-snapcraft@v1
        with:
          use_lxd: true

      - name: "Build license-manager snap"
        run: sg lxd -c 'snapcraft --use-lxd'

      - name: "Store snap filename for later use"
        if: ${{ success() }}
        id: vars
        shell: bash
        run: |
          echo "::set-output name=snap_file::$(ls *.snap)"
          echo "::set-output name=snap_hash::${{hashFiles('*.snap')}}"

      - name: Cache built snap
        if: ${{ success() }}
        id: license-manager-snap
        uses: actions/cache@v2
        with:
          path: ${{ steps.vars.outputs.snap_file }}
          key: license-manager-${{ hashFiles('*.snap') }}

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.

    outputs:
      snap_file: ${{ steps.vars.outputs.snap_file }}
      snap_hash: ${{ steps.vars.outputs.snap_hash }}

  push-license-manager-snap-to-s3:
    name: "Push snap to s3"
    runs-on: "ubuntu-latest"
    needs: [build]
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: "Restore the built snap"
        uses: actions/cache@v2
        with:
          path: ${{ needs.build.outputs.snap_file }}
          key: license-manager-${{ needs.build.outputs.snap_hash }}

      - name: "Push snap to s3"
        shell: bash
        run: |
          aws s3 cp ${{ needs.build.outputs.snap_file }} s3://omnivector-private-assets/snaps/license-manager/edge/

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
